### PR TITLE
upgrade to rails 4.2.3

### PR DESCRIPTION
**Pull request by swaroopmurthy**

### CODE REVIEW

**Comment by rosenfeld** [comment]
Merged, thanks. I just changed the commit description since it's AR which is upgraded rather than Rails...

**Comment by rosenfeld** [comment]
v4.2.3.1 is released by the way

**Comment by swaroopmurthy** [comment]
wow, that was quick...thanks!

**Comment by rosenfeld** [comment]
I'm already used to these kind of change :) Basically the only thing that I have to check is whether the internal implementation for the generator has changed or not in AR since the last version :) For a particular tiny method :) And of course I always manually test running and rolling back some migrations just to be sure before releasing. Thank you :)

**Pull request closed without merging**
